# This is a basic workflow to help you get started with Actions

name: Custom-CI

# Controls when the workflow will run
# Run for pushes and pulls on every branch and manually from the Actions tab
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # First job builds the environment
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install everything I need
      # Check I have python installed
      - run: |
          echo Cheking python install
          python --version

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
  
  # Second job runs MEMOTE
  memote:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - run: echo Running MEMOTE
  
  # Third job runs my custom tests
  custom-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - run: echo Running Custom Tests