# This is a basic workflow to help you get started with Actions

name: Custom-CI

# Controls when the workflow will run
# Run for pushes and pulls on every branch and manually from the Actions tab
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # First job builds the environment
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install everything I need
      - name: Install Dependencies
        run: |
          echo Installing MEMOTE
          python -m pip install --upgrade pip
          python -m pip install depinfo
          python -m pip install memote

      # Generate the memote report on the model
      - name: Generate MEMOTE Report
        run: memote -h

      # Run the custom tests
      - name: Run Custom Tests
        run: echo YAY :D